# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Audiobookshelf"
  org.opencontainers.image.description: "Self-hosted audiobook and podcast server"
  org.opencontainers.image.source: "https://github.com/samanthavbarron/hass-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
