# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Ad Begone"
  org.opencontainers.image.description: "Automatically detect and remove ads from podcast MP3 files"
  org.opencontainers.image.source: "https://github.com/samanthavbarron/hass-addons"
  org.opencontainers.image.licenses: "GPL-3.0"
